// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUe9WGJJUBjSpBHYzSyb1jbzJ5CMitev4',
    appId: '1:674162639546:web:6c69c928dc9b73b4d37883',
    messagingSenderId: '674162639546',
    projectId: 'e-commerce-app-9640b',
    authDomain: 'e-commerce-app-9640b.firebaseapp.com',
    databaseURL: 'https://e-commerce-app-9640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-9640b.appspot.com',
    measurementId: 'G-1BCXZVJV6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPdxNZC0j8Y-WzBzrnzXuOyqmJbM98lgk',
    appId: '1:674162639546:android:8fd2ee31ff8e2a80d37883',
    messagingSenderId: '674162639546',
    projectId: 'e-commerce-app-9640b',
    databaseURL: 'https://e-commerce-app-9640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-9640b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNda2p6C0f0X1y9-qZ9z7seH7C0ys0buw',
    appId: '1:674162639546:ios:4fb3b96c880e9761d37883',
    messagingSenderId: '674162639546',
    projectId: 'e-commerce-app-9640b',
    databaseURL: 'https://e-commerce-app-9640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-9640b.appspot.com',
    androidClientId: '674162639546-6g0c552odpi8cj3b0m10ma0qo4qa1rqa.apps.googleusercontent.com',
    iosClientId: '674162639546-hp9p50r01r49n56575t8mk30fksfv64d.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNda2p6C0f0X1y9-qZ9z7seH7C0ys0buw',
    appId: '1:674162639546:ios:dcca806ffbef9c47d37883',
    messagingSenderId: '674162639546',
    projectId: 'e-commerce-app-9640b',
    databaseURL: 'https://e-commerce-app-9640b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-9640b.appspot.com',
    androidClientId: '674162639546-6g0c552odpi8cj3b0m10ma0qo4qa1rqa.apps.googleusercontent.com',
    iosClientId: '674162639546-cuovlfhiilavlv7tfu63765ism5iljqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApplication.RunnerTests',
  );
}
